// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4JpDN70e5EmY_utCsbd__NAMJQZoAjls',
    appId: '1:705505923762:web:288d50d21b2e7379696fab',
    messagingSenderId: '705505923762',
    projectId: 'quiz-genius-588d5',
    authDomain: 'quiz-genius-588d5.firebaseapp.com',
    storageBucket: 'quiz-genius-588d5.appspot.com',
    measurementId: 'G-9HEX2TP62K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bpEvP4bq_aGC6WTWcANwUs5Vq21Ms88',
    appId: '1:705505923762:android:61998cdf04dcf5b9696fab',
    messagingSenderId: '705505923762',
    projectId: 'quiz-genius-588d5',
    storageBucket: 'quiz-genius-588d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZwQfcxpYs18QEw5-KRio9q3T5LzMZk0',
    appId: '1:705505923762:ios:f069eec8166819a3696fab',
    messagingSenderId: '705505923762',
    projectId: 'quiz-genius-588d5',
    storageBucket: 'quiz-genius-588d5.appspot.com',
    iosClientId:
        '705505923762-9tumdgj884f0750e9n4b028i95hh5ath.apps.googleusercontent.com',
    iosBundleId: 'com.yagnik.quizGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtZwQfcxpYs18QEw5-KRio9q3T5LzMZk0',
    appId: '1:705505923762:ios:07879b2faf7a67b8696fab',
    messagingSenderId: '705505923762',
    projectId: 'quiz-genius-588d5',
    storageBucket: 'quiz-genius-588d5.appspot.com',
    iosClientId:
        '705505923762-41erm37g6nn54hnqc9359fhuvpg64tp5.apps.googleusercontent.com',
    iosBundleId: 'com.yagnik.quizGenius.RunnerTests',
  );
}
